name: Notify Discord on Push with Diff

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (you can adjust this)

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
      # Step 2: Generate and save the payload
      - name: Generate Discord Payload
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # Get the latest commit details
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          REPO_URL="https://github.com/${{ github.repository }}"

          # Generate the diff for the latest commit
          DIFF = ALL_CHANGED_FILES
          # Create the Discord message payload
          PAYLOAD=$(cat <<EOF
          {
            "content": "**New Commit in [${{ github.repository }}](${REPO_URL}):**\\n
            - **Author:** ${COMMIT_AUTHOR}\\n
            - **Message:** ${COMMIT_MESSAGE}\\n
            - **Commit URL:** [View Commit](${COMMIT_URL})\\n
            - **Diff:**\\n\`\`\`diff\\n$DIFF\\n\`\`\`"
          }
          EOF
          )

          # Save the payload to a file
          echo "$PAYLOAD" > debug_payload.json

      # Step 3: Upload the payload as an artifact
      - name: Upload Payload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: debug-payload
          path: debug_payload.json
