name: Notify Discord on Push with Diff

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (you can adjust this)

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - uses: sarisia/actions-status-discord@v1
      if: always()
      id: webhook # set id to reference output payload later
      with:
        ack_no_webhook: true # set this to suppress warning
        # you can omit webhook input (or DISCORD_WEBHOOK environment variable)
      
    - run: npm install axios
    - uses: actions/github-script@v7
      env:
        WEBHOOK_PAYLOAD: ${{ steps.webhook.outputs.payload }}
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        script: |
          const axios = require("axios")
    
          const { WEBHOOK_PAYLOAD, WEBHOOK_URL } = process.env
    
          const payload = JSON.parse(WEBHOOK_PAYLOAD)
    
          // modify payload as you like
          delete payload.embeds[0].color
    
          // send to Discord
          axios.post(WEBHOOK_URL, payload)
